### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by thedarkjester** [on9commerce/blockchain-developer-bootcamp-final-project#1]
I pulled your project to evaluate it and am not able to install it/run the migrations.

Please could you make sure the package dependency list is in there as well as clearer instructions on how to install and get it running. Assume I am not a marker and another person learning from your repo.

**Comment by adrianteoyc** [comment]
I updated the repo with the package.json file as well as the READ.ME guide. Hope it works now on your local machine. Thank you.
